name: Build

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  tidy:
    name: Check go mod tidy
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version: 1.23
      - name: check go mod tidy
        run: |
          go mod tidy
          git diff --exit-code -- go.mod go.sum

  test:
    name: Golang tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version: 1.23
      - name: run golang tests
        run: go test ./...

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version: 1.23
      - name: build cli
        run: go build -o broke cmd/broke/main.go
